modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
[[mods]]
modId="linearexperience"
version="${file.jarVersion}"
displayName="Linear Experience"
updateJSONURL="https://raw.githubusercontent.com/DonovanDMC/LinearExperience/1.19/updates.json"
displayURL="https://github.com/DonovanDMC/LinearExperience"
itemIcon = "minecraft:anvil"
credits=""
authors="Donovan_DMC"
description='''
Tired of it taking weeks to reach level 538? Not anymore.
'''
[[dependencies.linearexperience]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"
[[dependencies.linearexperience]]
modId="minecraft"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="BOTH"